# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 5, "", "example.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rexample.proto\x12\x17tensorflow.core.example"\x1e\n\tFloatList\x12\x11\n\x05value\x18\x01 \x03(\x02\x42\x02\x10\x01"K\n\x07\x46\x65\x61ture\x12\x38\n\nfloat_list\x18\x03 \x01(\x0b\x32".tensorflow.core.example.FloatListH\x00\x42\x06\n\x04kind"\x9d\x01\n\x08\x46\x65\x61tures\x12?\n\x07\x66\x65\x61ture\x18\x01 \x03(\x0b\x32..tensorflow.core.example.Features.FeatureEntry\x1aP\n\x0c\x46\x65\x61tureEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .tensorflow.core.example.Feature:\x02\x38\x01">\n\x07\x45xample\x12\x33\n\x08\x66\x65\x61tures\x18\x01 \x01(\x0b\x32!.tensorflow.core.example.Featuresb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "example_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_FLOATLIST"].fields_by_name["value"]._loaded_options = None
    _globals["_FLOATLIST"].fields_by_name["value"]._serialized_options = b"\020\001"
    _globals["_FEATURES_FEATUREENTRY"]._loaded_options = None
    _globals["_FEATURES_FEATUREENTRY"]._serialized_options = b"8\001"
    _globals["_FLOATLIST"]._serialized_start = 42
    _globals["_FLOATLIST"]._serialized_end = 72
    _globals["_FEATURE"]._serialized_start = 74
    _globals["_FEATURE"]._serialized_end = 149
    _globals["_FEATURES"]._serialized_start = 152
    _globals["_FEATURES"]._serialized_end = 309
    _globals["_FEATURES_FEATUREENTRY"]._serialized_start = 229
    _globals["_FEATURES_FEATUREENTRY"]._serialized_end = 309
    _globals["_EXAMPLE"]._serialized_start = 311
    _globals["_EXAMPLE"]._serialized_end = 373
# @@protoc_insertion_point(module_scope)
